version: '3.9'
services:
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - pgsql
  php:
    build: ./php
    user: '1000:1000'
    volumes:
      - ./app:/var/www/html
      - ./php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./php/php.ini-production:/usr/local/etc/php/php.ini-production
      - ./php/docker-php-ext-sodium.ini:/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
  pgsql:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 54324:5432

  auth_pgadmin:
    container_name: auth_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "52826:80"